# Generated by Django 4.2.1 on 2024-03-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTravelAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField(max_length=255)),
                ('ending_location', models.CharField(max_length=255)),
                ('starting_kilometer', models.IntegerField(blank=True, null=True)),
                ('ending_kilometer', models.IntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_allowances', to='api.employee')),
            ],
        ),
    ]
