# Generated by Django 4.2.1 on 2024-03-19 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeetravelallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='visiting_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetravelallowance',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=20),
        ),
    ]
